### ISSUE TITLE
LRS Endpoint not working

### ISSUE THREAD

**Issue by yugandhararao** [trax-project/trax-lrs#11]
Hi, Thanks for providing such a wonderful open-source lrs. I have installed lrs properly but endpoint not working. When access endpoint http://localhost/traxlrs/trax/ws/xapi/about it showing below error
Not Found
The requested URL /traxlrs/trax/ws/xapi/about was not found on this server.

Apache/2.4.27 (Win64) PHP/7.1.9 Server at localhost Port 80.

and also I configured lrs endpoint in launch storyline it showing "There was a problem communicating with the Learning Record Store. Your results may not be saved. Please check your internet connection and try again.".

Please help me. Thank you in Advance.
Yugandhar

**Comment by sfraysse** [comment]
Hi,
Please, could you try to open http://localhost/traxlrs/public/trax/ws/xapi/about in your browser?
Doc: https://github.com/trax-project/trax-lrs#public-directory

**Comment by yugandhararao** [comment]
Hi,
Thanks for the comment. 
When access http://localhost/traxlrs/trax/ws/xapi/about it showing below error
Not Found
The requested URL /traxlrs/trax/ws/xapi/about was not found on this server.

Apache/2.4.27 (Win64) PHP/7.1.9 Server at localhost Port 80.

**Comment by sfraysse** [comment]
Hi,
Once again, could you try the following URL: http://localhost/traxlrs/public/trax/ws/xapi/about
Note that I inserted **public** in your URL...

**Comment by yugandhararao** [comment]
Hi sfraysse,
Sorry, I didn't notice the URL update.  
Thank you so much for guide me.  It's working perfectly.  Once again thanks for providing nice lrs solution.

**Comment by sfraysse** [comment]
You are welcome
