### ISSUE TITLE
Installation en local

### ISSUE THREAD

**Issue by JmC-fr** [trax-project/trax-lrs#14]
Bonjour Sébastien,

Trax m'a l'air d'être un super projet, mais j'aurai aimé le tester en local, sur une stack [Laragon](https://laragon.org/).

J'ai donc configuré un Apache 2.2.41, PHP 7.4.2 (avec pdo_mysql) et MySql 5.7.28, mais impossible d'initialiser la base avec "php artisan migrate"
J'ai toujours la même erreur :
```
    Illuminate\Database\QueryException  : 
    could not find driver (SQL: select * from information_schema.tables where table_schema = trax and table_name = migrations)
    at D:\Projets\Trax\www\vendor\laravel\framework\src\Illuminate\Database\Connection.php:664
```

J'ai pourtant bien `API Extensions  = mysqli,pdo_mysql`
J'ai testé avec plusieurs version de MySQL, mais rien n'y fait ...

Y a-t-il un autre moyen d'initialiser la base ?

**Comment by sfraysse** [comment]
Bonjour,
`php artisan migrate` utilise PHP CLI, dont la configuration peut être différente du PHP utilisé par Apache. Vérifier que pdo_mysql est bien activé pour PHP CLI.

**Comment by JmC-fr** [comment]
Merci beaucoup Sébastien,

Tout fonctionne bien maintenant.

**Comment by sfraysse** [comment]
De rien. Pour info, le développement de Trax LRS 2.0 a commencé et devrait voir le jour dans le courant de l'année. Cette nouvelle version devrait intégrer de nombreux retours d'expérience et de nouvelles idées.
N'hésitez pas à faire part de vos souhaits ici : https://github.com/trax-project/trax-lrs/issues/12
