### ISSUE TITLE
Problème durant l'installation

### ISSUE THREAD

**Issue by AspiDev** [trax-project/trax-lrs#15]
Bonjour,

J'essaie d'installer TRAX sur un serveur mais il semble s'arrêter durant l'installation après trax/api

Il me donne l'erreur suivante: 
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In PackageManifest.php line 122:
                         
  Undefined index: name  
                         

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Pouvez-vous m'indiquer la marche à suivre?

merci par avance

François

**Comment by sfraysse** [comment]
Bonjour François,

A priori, il y a un problème avec une récente mise à jour de Composer :
Lisez ceci : https://laracasts.com/discuss/channels/laravel/packagemanifestphp-undefined-index-name

Quelle est votre version de Composer ?
Peut-être pourriez-vous essayer de mettre à jour Composer comme préconisé dans la discussion ?

Tenez-moi au courant.

Sébastien

**Comment by AspiDev** [comment]
Bonjour et merci de votre rapidité.

Bon je ne suis pas un roi de la ligne de commande loin de la mais je viens de trouver la version qui est en effet la 2.0 comme indiquée dans le thread. Je vais tenter la mise à jour et je vous tiens au courant

François

**Comment by AspiDev** [comment]
Bonjour,

A priori je ne pourrai pas installer ce LRS sur mon serveur. Il s'agit d'un VPS chez OVH mais avec Plesk. Je n'ai pas l'accès en root. Je vais essayer de trouve rune autre solution car je souhaiterais vivement le tester. Merci encore pour votre support
