### ISSUE TITLE
Installer Trax sur un réseau cloisonné

### ISSUE THREAD

**Issue by Laurent37000** [trax-project/trax-lrs#16]
Bonjour,

Est il possible d'installer TRAX sur un réseau cloisonné déconnecté d'internet.
Si oui, existe t-il une documentation pour réaliser cette opération ?

Merci pour votre aide et bravo pour vos travaux !

Laurent

**Comment by sfraysse** [comment]
Bonjour,
Vous pouvez dérouler la première étape sur un poste connecté - `composer create-project --prefer-dist --stability rc trax/lrs traxlrs` - puis récupérer le dossier et le copier sur votre poste déconnecté. La suite de la procédure est offline.

**Comment by Laurent37000** [comment]
Bonjour

Nous déroulons toujours la procédure...

Notre infrastructure cloisonnée nous complique la tâche...mais votre commentaire nous a conforté dans la méthode à adopter. Faire et défaire c'est travailler !

Je vous tiens informé de nos conclusions.

Merci pour votre aide.

Laurent
