### ISSUE TITLE
Page blanche

### ISSUE THREAD

**Issue by Laurent37000** [trax-project/trax-lrs#17]
Bonjour à tous,

Nous avons réalisé l'installation sur un Debian 9.

Lorsque nous avons fini la configuration, nous lançons un navigateur et depuis l'adresse "locahost/index.php" située dans le dossier "public" de l'installation nous obtenons une page blanche (vide).

Avons nous raté une subtilité, étape, ...?

Merci pour votre aide,

Laurent

**Comment by sfraysse** [comment]
Bonjour,
C'est `localhost/public` si installé à la racine de votre localhost, et non `locahost/index.php`.
Si votre serveur pointe déjà vers le dossier public, alors c'est juste `localhost`.
Vérifiez aussi que le module `mod_rewrite` d'Apache est bien activé.

**Comment by Laurent37000** [comment]
Bonsoir,
ok nous essaierons cette configuration demain matin et nous vous tiendrons au courant de la conclusion.
Merci pour votre aide.
Très cordialement.
Laurent


⁣Télécharger BlueMail pour Android ​

Le 4 juin 2020 à 17:39, à 17:39, "Sébastien FRAYSSE" <notifications@github.com> a écrit:

**Comment by Laurent37000** [comment]
Bonjour,

Donc suite à vos indications :

1. **localhost** nous amène à **localhost/login** mais avec une page vide (blanche)
2. Après vérification `mod_rewrite` est bien activé.

Ci-joint notre config APACHE

Merci pour votre aide.

Cordialement,

![sites-enable_000-default conf](https://user-images.githubusercontent.com/64526138/83855160-faadc500-a717-11ea-9036-830f52f3b576.PNG)
Laurent

**Comment by sfraysse** [comment]
Ok, votre root pointe sur `public` donc c'est bon.
La redirection vers `localhost/login` est normale.
La page blanche indique un problème de config de votre serveur.
Passez bien en revue tous les prérequis de la procédure d'install (version PHP et modules PHP en particulier).
Vérifiez bien les droits d'écriture sur les dossiers comme indiqué (forcez à 777 en cas de doute pour tester) : ça vient très souvent de là. 
Si vous avez toujours le problème, dans le fichier de config `.env`, passez le paramètre `APP_DEBUG=false` à `APP_DEBUG=true`.
Explorez les logs d'erreur de l'appli dans `storage/logs/laravel`.

**Comment by Laurent37000** [comment]
Sébastien,

Merci pour votre aide. 

En fait les droits n'étaient pas bien positionnés sur "`storage`" et "`public`".
Du coup un `chmod 777 -R` à résolu le problème : Nous obtenons la fenêtre de Login...

On passe à la suite...à très bientôt ! 

Merci encore 

Laurent

**Comment by sfraysse** [comment]
Ok super, bonne utilisation.
Pour mémoire, TRAX LRS 2.0 est actuellement en cours de dév et devrait sortir vers septembre.
Alors n'hésitez pas à partager votre retour d'expérience afin d'intégrer d'éventuelles idées d'ici là.
https://github.com/trax-project/trax-lrs/issues/12
