### ISSUE TITLE
What is API url to send data to the LRS

### ISSUE THREAD

**Issue by Piou-piou** [trax-project/trax-lrs#2]
Hello,

I am trying your LRS solution and I can't find any endpoint to send data of my xAPI module.
Does it exist ? If yes could you put it in README please :)

**Comment by tazorax** [comment]
You can see it in the bottom of the "Basic HTTP Clients" page.
For example, if our domain is trax.test, the LRS endpoint should be http://trax.test/trax/ws/xapi

**Comment by Piou-piou** [comment]
Thanks for your help
