### ISSUE TITLE
PHP ARTISAN MIGRATE

### ISSUE THREAD

**Issue by Chrystele3700** [trax-project/trax-lrs#20]
Bonjour M. Fraysse,

Nous nous tournons de nouveau vers vous car nous bloquons complètement sur l’installation du traxlrs avec une base mysql.
L’installation **originale** a été effectuée comme indiqué sur Github à l’exception de la version PHP 7.3.
Puis, nous avons désinstallé cette version pour mettre la 7.1 (celle qui est en place actuellement).
Les erreurs que vous avez pu lire dans le précédent post de Laurent37000 ainsi que dans celui d’aujourd’hui sont identiques, malgré la version 7.1 de PHP.
Vous trouverez en PJ :
-	Le fichier .env avec la modification concernant la valeur de DB_MARIADB=1 (cela avait également été testé auparavant sans succès) ;
-	Les copies d’écran des erreurs remontées suite à la commande « php artisan migrate » et du fichier Connection.php dont il est fait mention dans les erreurs citées.
Lorsque l’on execute php artisan migrate, la table migrations est bien créée (P.J 1) mais génère une erreur (P.J 1 et P.J 2). La référence au fichier Connection.php ligne 452 se trouve dans la PJ nommée « Connection.php ».
Nous ne savons plus de quel côté chercher.
Vous trouverez également le phpinfo.

Nous vous remercions par avance pour votre aide.

![Fichier env](https://user-images.githubusercontent.com/67093912/84992685-8415bc00-b148-11ea-8c89-f297a6710349.PNG)
![PJ1](https://user-images.githubusercontent.com/67093912/84992698-8710ac80-b148-11ea-9fe2-ea77234911e1.PNG)
![PJ2](https://user-images.githubusercontent.com/67093912/84992710-8aa43380-b148-11ea-954d-4d38361b3c98.PNG)
![Connection php](https://user-images.githubusercontent.com/67093912/84992720-8e37ba80-b148-11ea-8b49-70e2c2aec066.png)
[phpinfo.pdf](https://github.com/trax-project/trax-lrs/files/4797062/phpinfo.pdf)

**Comment by sfraysse** [comment]
Bonjour. Il s'agit toujours d'un problème lié à votre base de données.

Pouvez-vous taper : `mysql --version` s'il vous plait ?

**Comment by sfraysse** [comment]
Je m'avance peut-être un peu mais ça me fait penser à une version de MariaDB qui ne serait pas à jour.
Prérequis : MariaDB 10.2.8+
`mysql --version` permettrait de vérifier ce point.

**Comment by Chrystele3700** [comment]
En effet, ma version est de MariaDB est la 10.1.44

**Comment by sfraysse** [comment]
Je sais que c'est un peu contraignant mais il est primordial de bien vérifier tous les prérequis d'installation avant de lancer la procédure. Dans votre cas :
- Apache 2.4 avec mod_rewrite
- PHP 7.1.9+ avec OpenSSL, Mbstring, Tokenizer, XML, Ctype, JSON, Curl, BCMath, Exif, PDO_MySQL
- MariaDB 10.2.8+

Vérifiez bien que la config vaut à la fois pour PHP CLI (ligne de commande) et PHP Web (Apache) car il y a en général 2 config dissociées (2 PHP.ini).

Quand tout est vérifié, repartez d'une installation fraîche (ne pas essayer de réinstaller sur une install qui a échoué).

Ne pas lancer les commandes d'optimisation (`php artisan route:cache` et `php artisan config:cache`) tant que vous êtes en mode test, car ces commandes génèrent un cache qu'il faut penser à réinitialiser à chaque modif de la config. Ces commandes ne sont pas nécessaires un fonctionnement de l'appli.

Concernant l'utilisation de Github, merci de continuer à utiliser le même ticket et de ne pas en créer un nouveau pour le suivi de votre situation.

Bon courage, vous y êtes presque ! Tenez-moi au courant.

**Comment by Chrystele3700** [comment]
M. Fraysse,

Encore merci. Cela fonctionne!
La page concernant le trax apparait bien dans le navigateur.
Je viens à l'instant de modifier le mot de passe d'admin.

**Comment by sfraysse** [comment]
Super ! Je clos le ticket. N'hésitez pas le rouvrir si vous avez un autre problème.

Gardez à l'esprit qu'une version 2.0 va arriver à l'automne.
Le site Web vient d'être mis à jour pour refléter les évolutions à venir : http://traxlrs.com

N'hésitez pas à revenir vers moi en privé pour partager votre retour d'expérience.

Je vous souhaite une bonne exploration !
