### ISSUE TITLE
Connexion LMS-LRS 

### ISSUE THREAD

**Issue by Chrystele3700** [trax-project/trax-lrs#22]
Bonjour M. Fraysse,

Je fais de nouveau appel à vous.
J'ai installé un TRAX-LRS, avec  Mariadb 10.3 sur une Vm. 
Un compte client TRAX + Mot de Passe y a été créé.
Sur une autre Vm est installé un LMS (Ilias V6).
La connexion entre les 2 ne fonctionne pas.
Sur le LMS, déclaration d'un LRS xAPI/cmi5 avec comme paramètres : endpoint:http://@LRS/trax/ws/xapi.
Login: trax, Pswd: mot de passe précédemment enregistré.

Pour information, sur le LRS, partie "Clients Basic HTTP", le LRS endpoint est: http://localhost/trax/ws/xapi.

Je vous remercie pour votre aide.

**Comment by sfraysse** [comment]
Bonjour,
Il m'est difficile de vous apporter une réponse qui dépend de votre architecture et des droits qui y sont liés.
Quelques vérifications de base que vous pouvez faire avant toute chose :
- Vérifier que l'URL http://localhost/trax/ws/xapi/about est bien accessible (elle ne requiert pas d'authentification) depuis vm LRS et depuis votre VM cliente.
- Tester ensuite l'accès à http://localhost/trax/ws/xapi/statements en passant cette fois les entêtes d'authentification Basic HTTP.

**Comment by Chrystele3700** [comment]
M.Fraysse,
Merci pour votre réponse.
Je teste et je continue de creuser.
Cordialement.

**Comment by Chrystele3700** [comment]
Bonjour M.Fraysse,

Voici le résultat de mes recherches effectuées sur le LRS d’une part, et le LMS d’autre part (installations faites sur réseau cloisonné).
L’URL http://.../trax/ws/xapi/about est accessible par les 2 serveurs mais avec des erreurs, identiques à celles relevées dans le fichier joint.
L’URL http://.../trax/ws/xapi/statements n’est accessible par aucun des 2 serveurs.

J’ai donc entrepris de refaire ces tests sur la machine initiale reliée à Internet, et qui m’a permis d’installer, par la suite, le TRAX LRS sur le réseau cloisonné.
En utilisant un « LogLevel  trace 8 », j’ai obtenu les résultats collectés dans le fichier joint.

[error.log_access.log.pdf](https://github.com/trax-project/trax-lrs/files/5069297/error.log_access.log.pdf)


Je vous remercie par avance pour votre aide.

Cordialement.

**Comment by sfraysse** [comment]
Bonjour,

Pour ce qui concerne l'affichage dans le navigateur :
- About : c'est OK
- Statements : il faut passer le header Authorization (avec les données BasicHTTP), ainsi que le header X-Experience-API-Version qui est obligatoire pour tout échange avec une API (cf spec)

Vous pouvez utiliser un logiciel comme Postman pour tester l'accès en passant les bons headers.

Pour les problématiques de communications propres à votre infrastructure, encore une fois, il m'est difficile de vous répondre.

**Comment by Chrystele3700** [comment]
Bonjour M. Fraysse,

Merci pour votre note.
Je poursuis les tests.

Cordialement.
