### ISSUE TITLE
Transaction not found

### ISSUE THREAD

**Issue by JD76** [trax-project/trax-lrs#25]
Hi, I just tried to install trax-lrs. All things seems to work fine, but when I try to add a client I catch an error. 
In the Chrome inspector, the basic-clients call show this response:

{
    "message": "Trait 'Trax\\DataStore\\Utils\\Transaction' not found",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalErrorException",
    "file": "[myaddress]/traxlrs/vendor/trax/framework/data-store/src/Http/Controllers/DataWsController.php",
    "line": 15,
    "trace": []
}

I already tried this call (I saw it in another issue):  http://localhost/trax/ws/xapi/statements
And the answer is the same:
"Trait 'Trax\DataStore\Utils\Transaction' not found"

Can you help me?
Thank you very much
best regards
Ursula

**Comment by sfraysse** [comment]
Hi Ursula,

Could you confirm that you are using a MongoDB database, please?

If yes, be aware that MongoDB support will be dropped in the next release, because of a lack of maintenance on the related PHP package.

So my best advice is to switch to MySQL, MariaDB or PostgreSQL.
If MongoDB is a requirement for you, look at Learning Locker.

Sébastien

**Comment by JD76** [comment]
Hi, no, I'm using MariaDB.
Thanks
Ursula

**Comment by JD76** [comment]
Hi, I attach the screenshot of the Chrome inspector when I call /trax/ui/account/basic-client/crud
I don't know if it can help.
![errorTrax](https://user-images.githubusercontent.com/6704707/92209624-9d97eb80-ee8d-11ea-8146-c5f0f13d6f51.JPG)

**Comment by sfraysse** [comment]
Hi Ursula,

The console doesn't really help me, but your first message yes.
It looks like something was broken in the source code. 

Did you change something somewhere in the code of the Laravel project?

Could you check that you have the following file in your installation:
`./vendor/trax/framework/data-store/src/Stores/Utils/Transaction.php`

If yes, could you go to the root of the project in your console and type `composer dumpautoload`.

Sébastien

**Comment by JD76** [comment]
Hi Sébastien, 
thanks for your support! The file was there and I launch composer dumpautoload and now it works!
Thank you very much,
best regards
Ursula

**Comment by sfraysse** [comment]
Great! I close this issue.

**Comment by oaubert** [comment]
This error is still there, depending on the machine configuration. I am trying to dockerize it and am facing multiple issue, both with composer 2.0.8 and (after composer self-update --stable) composer 2.0.12 :+1: 
- on `composer create-project` it outputs (in the autoload generation phase)
<code>
Generating optimized autoload files
Class Trax\Foundation\Exceptions\OptionNotFoundException located in ./vendor/trax/framework/foundation/src/Exceptions/OptionException.php does not comply with psr-4 autoloading standard. Skipping.
Class Trax\DataStore\Utils\Transaction located in ./vendor/trax/framework/data-store/src/Stores/Utils/Transaction.php does not comply with psr-4 autoloading standard. Skipping.
</code>
which makes Transaction not referenced afterwards. 

- additionnally, there is an error in the post-autoload script:
<code>
> @php artisan package:discover --ansi
In PackageManifest.php line 122:                       
  Undefined index: name  
</code>

Both errors are suppressed (actually the first one is a Deprecation warning) when downgrading composer to 1.10.20. I think that the dependency on the 1.* version of composer should be mentioned in the README (or the code should be fixed to work with composer 2.*).

**Comment by sfraysse** [comment]
Hi,

Thanks for your feedback.

This project is not compatible with Composer 2.x and this will not be fixed.

Please, give a try to TRAX LRS 2.0: https://github.com/trax-project/trax2-starter-lrs
It is compatible with Composer 2.x.
