### ISSUE TITLE
The keyword to use with PostgreSQL should be "pgsql" instead of "pqsql"

### ISSUE THREAD

**Issue by camaer** [trax-project/trax-lrs#3]
In the README.md:

The keyword to use with PostgreSQL should be "pgsql" instead of "pqsql" in the .env file

![screen shot 2019-02-07 at 5 23 17 pm](https://user-images.githubusercontent.com/35572989/52446848-2d808280-2afd-11e9-8972-f9751399348d.png)

**Comment by camaer** [comment]
Thanks !

**Comment by sfraysse** [comment]
You are welcome. Many thanks for your feedbacks!
