### ISSUE TITLE
Use relative URLs for vuejs ressources

### ISSUE THREAD

**Issue by biwano** [trax-project/trax-lrs#4]
The ressources provided by Trax for VueJS ressources are absolute to the host root. Thus Trax cannot work if it is not installed at the root of the host.

In practice I would like:
  <script src="js/trax-ui.js?id=cde456d00440fb334bf3"></script>
Instead of
  <script src="/js/trax-ui.js?id=cde456d00440fb334bf3"></script>

**Comment by sfraysse** [comment]
Thanks for your feedback.
Installing the last version( RC4) should solve your issue.
