### ISSUE TITLE
Remove MongoDB requirement from the default install

### ISSUE THREAD

**Issue by camaer** [trax-project/trax-lrs#6]
Hello,

It seems like composer need mongodb and it's php extension.

``` 
 Problem 1
    - Installation request for mongodb/mongodb 1.3.2 -> satisfiable by mongodb/mongodb[1.3.2].
    - mongodb/mongodb 1.3.2 requires ext-mongodb ^1.4.0 -> the requested PHP extension mongodb is missing from your system.
  Problem 2
    - mongodb/mongodb 1.3.2 requires ext-mongodb ^1.4.0 -> the requested PHP extension mongodb is missing from your system.
    - jenssegers/mongodb v3.4.5 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.3.2].
    - Installation request for jenssegers/mongodb v3.4.5 -> satisfiable by jenssegers/mongodb[v3.4.5].
```

If I plan to use mysql or postgresql my understanding is that I need to install mongodb even if I don't plan on using it ?

Would it be possible to bypass this requirement to prevent installing 250mb+ for nothing ?

Thanks !

**Comment by camaer** [comment]
I was able to bypass the check of dependencies by adding the following parameters in composer:
`--ignore-platform-reqs`

**Comment by sfraysse** [comment]
You are right, 

jenssegers/mongodb PHP package is installed by default to support MongoDB config, and it requires the mongodb PHP extension.

Do you think I should remove this package from the default install and let people install it if they want to use MongoDB?

**Comment by camaer** [comment]
I think this would be a better yes. This way if people need mongodb we can update the doc to show how to install the package and for people like us that use mysql or postgres we no longer need to install a package we don't need.

**Comment by sfraysse** [comment]
This makes sense. I will do that for the next release.
Thanks for your feedback.

**Comment by camaer** [comment]
Thanks for your awesome work !

**Comment by sfraysse** [comment]
The 1.0.0-rc.5 release solves this issue.
