### ISSUE TITLE
Image Docker

### ISSUE THREAD

**Issue by titanix** [trax-project/trax-lrs#7]
Bonjour à vous,
le projet est intéressant mais un peu complexe à déployer en particulier pour qui a pas ou peu d'expérience avec Laravel.
Je pense qu'il serait intéressant de fournir un script docker pour construire une image Docker ainsi qu'un fichier pour docker-compose afin d'avoir une solution qu'on puisse tester en une ligne de commande.
Personnellement j'avais besoin d'un LRS de test, mais je me suis arrêté après une demi-heure de tentative d'installation.
Cordialement.

**Comment by sfraysse** [comment]
Bonjour et merci pour cette proposition.

Concernant l'installation standard, plusieurs difficultés ont été remontées :
- Extensions PHP MongoDB requises même lorsque l'on ne souhaite pas utiliser Mongo. Ce point va être traité en retirant le prérequis Mongo.
- URL de l'appli devant être suivie de "public" lorsque le serveur ne pointe pas déjà sur ce dossier. Ce point mérite d'être mieux documenté.

Si vous avez rencontré d'autres difficultés, je suis preneur afin d'améliorer l'installation et/ou la documentation.

Concernant Docker, ce n'est pas à l'ordre du jour à court terme, mais si vous (ou quelqu'un d'autre) souhaitez faire quelque chose et de le partager, welcome.

**Comment by titanix** [comment]
Ah oui la fameuse extension Mongo, j'ai déjà eu ce problème à gérer sur un projet.
Concernant l'image Docker j'avais commencé à m'en charger moi-même mais j'ai lâché l'affaire afin de la terminer. Je posterai une PR si jamais je la termine.

**Comment by sfraysse** [comment]
Ca serait super ! Merci.
